apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chihuo

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - api.yaml
  - frontends.yaml
  - services.yaml
  - ingress.yaml

images:
  - name: chihuo/api
    newName: chihuo/api
    newTag: local
  - name: chihuo/consumer
    newName: chihuo/consumer
    newTag: local
  - name: chihuo/merchant
    newName: chihuo/merchant
    newTag: local
  - name: chihuo/rider
    newName: chihuo/rider
    newTag: local
  - name: chihuo/admin
    newName: chihuo/admin
    newTag: local
