import type { MerchantSnapshot } from './types'

export const mockMerchantSnapshot: MerchantSnapshot = {
  demands: [
    {
      id: 'merchant-demand-1',
      title: '低油轻食工作餐',
      category: '午餐',
      location: '科技园 A 区',
      schedule: '工作日 11:30–12:30',
      joined: 28,
      target: 40,
      budget: '¥22–28',
      deadline: '今天 18:00 截止',
      tags: ['低油', '定量 350g', '不含花生'],
      fit: '高匹配',
      fitNote: '你的现有鸡胸套餐可复用 80% 原料与包装。',
      status: '待报价',
    },
    {
      id: 'merchant-demand-2',
      title: '无乳制品早餐',
      category: '早餐',
      location: '南站办公区',
      schedule: '工作日 08:00–09:00',
      joined: 22,
      target: 30,
      budget: '¥15–20',
      deadline: '明天 12:00 截止',
      tags: ['无乳制品', '高蛋白', '可带走'],
      fit: '高匹配',
      fitNote: '现有杂粮饭和鸡肉配方可以直接调整。',
      status: '已报价',
    },
    {
      id: 'merchant-demand-3',
      title: '周三家庭小份菜',
      category: '家庭餐',
      location: '云杉社区',
      schedule: '周三 17:30–18:30',
      joined: 25,
      target: 25,
      budget: '¥48–60',
      deadline: '已达标 · 今日 16:00 截止',
      tags: ['少盐', '两菜一汤', '小份量'],
      fit: '可尝试',
      fitNote: '需要新增汤品分装，预估备餐工时增加 20 分钟。',
      status: '已转预售',
    },
    {
      id: 'merchant-demand-4',
      title: '周末低糖烘焙拼单',
      category: '烘焙',
      location: '望江路 3 公里内',
      schedule: '周六 14:00–16:00',
      joined: 7,
      target: 20,
      budget: '¥18–25',
      deadline: '周五 12:00 截止',
      tags: ['低糖', '独立包装'],
      fit: '需评估',
      fitNote: '当前订单量偏小，建议等待需求继续聚合。',
      status: '待报价',
    },
  ],
  quotes: [
    {
      id: 'quote-1',
      demandId: 'merchant-demand-2',
      demandTitle: '无乳制品早餐',
      submittedAt: '今天 08:42',
      price: 18,
      grams: 260,
      minOrder: 20,
      status: '审核中',
      note: '鸡肉杂粮能量包，独立封装，早餐时段集中配送。',
    },
    {
      id: 'quote-2',
      demandId: 'merchant-demand-3',
      demandTitle: '周三家庭小份菜',
      submittedAt: '昨天 16:08',
      price: 56,
      grams: 820,
      minOrder: 25,
      status: '已入选',
      note: '番茄炖牛腩、清炒时蔬、菌菇汤，两菜一汤分装。',
    },
  ],
  productionOrders: [
    {
      id: 'CH-20260902-018',
      product: '香草鸡胸藜麦饭',
      location: '科技园 A 区',
      quantity: 28,
      paid: 26,
      status: '制作中',
      window: '今天 11:30–12:30',
      batch: 'HX-0902-A01',
      note: '低油 · 380g · 不含花生',
    },
    {
      id: 'CH-20260901-031',
      product: '云杉家常两菜一汤',
      location: '云杉社区北门',
      quantity: 25,
      paid: 56,
      status: '待生产',
      window: '周三 17:30–18:30',
      batch: '待创建',
      note: '少盐 · 两人份 · 分装配送',
    },
    {
      id: 'CH-20260831-074',
      product: '鸡肉杂粮能量包',
      location: '南站办公区',
      quantity: 22,
      paid: 18,
      status: '待交接',
      window: '今天 08:00–09:00',
      batch: 'HX-0902-B02',
      note: '无乳制品 · 高蛋白',
    },
  ],
  qualifications: [
    { name: '营业执照', status: '已通过', expires: '2028-04-18', updated: '2026-08-20 更新' },
    { name: '食品经营许可证', status: '已通过', expires: '2027-11-02', updated: '2026-08-20 更新' },
    { name: '门店与加工地址', status: '已通过', expires: '长期有效', updated: '2026-08-21 核验' },
    { name: '食品安全负责人信息', status: '待补充', expires: '长期有效', updated: '请补充联系电话' },
  ],
  safetyRecords: [
    {
      id: 'safe-1',
      type: '批次留档',
      title: 'HX-0902-A01 低油鸡胸藜麦饭',
      date: '2026-09-02 10:58',
      owner: '王师傅',
      status: '已完成',
      detail: '原料、称重、包装与配送交接记录已上传。',
    },
    {
      id: 'safe-2',
      type: '日常检查',
      title: '开档前环境与设备检查',
      date: '2026-09-02 07:18',
      owner: '李梅',
      status: '已完成',
      detail: '冷藏柜 3.8°C，消毒记录正常，明厨亮灶在线。',
    },
    {
      id: 'safe-3',
      type: '投诉跟进',
      title: '订单 CH-20260901-031 包装破损',
      date: '2026-09-01 18:47',
      owner: '平台客服',
      status: '处理中',
      detail: '已联系骑手和消费者，等待补充外包装照片。',
    },
  ],
}
