import type { ConsumerSnapshot, Demand, Product } from './types'

export const mockConsumerSnapshot: ConsumerSnapshot = {
  demands: [
    {
      id: 'demand-1',
      title: '低油轻食工作餐',
      category: '午餐',
      location: '科技园 A 区',
      schedule: '工作日 11:30–12:30',
      target: 40,
      joined: 28,
      budget: '¥22–28',
      status: '聚合中',
      tags: ['低油', '定量 350g', '不含花生'],
      description: '希望主食、蛋白质和蔬菜比例清晰，少油烹饪，午休期间集中配送。',
      merchantHint: '已聚合 28 份有效需求，达到 40 份后进入商家报价。',
    },
    {
      id: 'demand-2',
      title: '周三家庭小份菜',
      category: '家庭餐',
      location: '云杉社区',
      schedule: '周三 17:30–18:30',
      target: 25,
      joined: 25,
      budget: '¥48–60',
      status: '已达标',
      tags: ['少盐', '两菜一汤', '小份量'],
      description: '适合两位成人的晚餐组合，希望菜品清淡、分装清楚，回家即可加热。',
      merchantHint: '需求已达标，正在等待商家提交最终规格和价格。',
    },
    {
      id: 'demand-3',
      title: '无乳制品早餐',
      category: '早餐',
      location: '南站办公区',
      schedule: '工作日 08:00–09:00',
      target: 30,
      joined: 22,
      budget: '¥15–20',
      status: '即将开售',
      tags: ['无乳制品', '高蛋白', '可带走'],
      description: '需要一份方便带走的早餐，避开牛奶、奶油和芝士，口味偏清爽。',
      merchantHint: '禾下餐桌已提交预售方案，等待你确认规格。',
    },
    {
      id: 'demand-4',
      title: '周末低糖烘焙拼单',
      category: '烘焙',
      location: '望江路 3 公里内',
      schedule: '周六 14:00–16:00',
      target: 20,
      joined: 7,
      budget: '¥18–25',
      status: '聚合中',
      tags: ['低糖', '独立包装'],
      description: '希望口感不甜腻，适合下午茶分享，最好可以独立包装。',
      merchantHint: '还差 13 份，邀请同事或邻居加入可更快达标。',
    },
  ],
  products: [
    {
      id: 'product-1',
      title: '香草鸡胸藜麦饭',
      merchant: '禾下餐桌',
      price: 26,
      originalPrice: 29,
      grams: 380,
      stock: 32,
      delivery: '今日 11:30–12:30',
      tags: ['低油', '不含花生', '批次可查'],
      accent: 'sage',
      demandId: 'demand-1',
    },
    {
      id: 'product-2',
      title: '云杉家常两菜一汤',
      merchant: '邻里厨房',
      price: 56,
      originalPrice: 62,
      grams: 820,
      stock: 18,
      delivery: '周三 17:30–18:30',
      tags: ['少盐', '两人份', '分装配送'],
      accent: 'apricot',
      demandId: 'demand-2',
    },
    {
      id: 'product-3',
      title: '鸡肉杂粮能量包',
      merchant: '禾下餐桌',
      price: 18,
      originalPrice: 20,
      grams: 260,
      stock: 24,
      delivery: '明日 08:00–09:00',
      tags: ['无乳制品', '高蛋白', '可带走'],
      accent: 'blue',
      demandId: 'demand-3',
    },
  ],
  orders: [
    {
      id: 'CH-20260902-018',
      product: '香草鸡胸藜麦饭',
      merchant: '禾下餐桌',
      quantity: 1,
      amount: 29.5,
      status: '配送中',
      time: '今天 11:30–12:30',
      address: '科技园 A 区 2 号楼前台',
    },
    {
      id: 'CH-20260901-031',
      product: '云杉家常两菜一汤',
      merchant: '邻里厨房',
      quantity: 1,
      amount: 59,
      status: '待成团',
      time: '周三 17:30–18:30',
      address: '云杉社区北门',
    },
  ],
}

export function cloneDemand(demand: Demand, joined = 1): Demand {
  return { ...demand, joined: Math.min(demand.target, demand.joined + joined) }
}
